- name: MultiPlay
  hosts: local
  connection: local  # Managing its own node, no need for credentials
  tasks:
    - name: play1
      ansible.builtin.debug:
        msg: "Hello from Play1"



- name: MultiPlay2
  hosts: local
  connection: local  #managing its own node not need of any credentials
  tasks:
    - name: play2
      ansible.builtin.debug:
       msg: "Hello from Play2"


     # ansible-playbook -i inventory.init multi-play.yaml  ( no need of username and pwd as it is local host)