- name: Ngnix
  hosts: web
  become: yes  #sudo access  i.e -b
  tasks:
  - name: Install Ngnix
    ansible.builtin.package:
     name: nginx
     state: present # to install, absent to remove
  - name: Start Ngnix
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes  #to enable the service automatically
  # ansible-playbook -i inventory.ini -e ansible_user=ec2_user -e ansible_password=DevOps321 ngnix.yaml




     