- name: Variable from Prompt
  hosts: local
  connection: local
  tasks:
   - name: Print the variables from Prompt
     ansible.builtin.debug:
      msg: "Name of the Course is {{ COURSE }} , duration of the couse is {{ DURATION }} trained by {{ TRAINER }}" 


#if no where varaibles are defined then we can provide during the cmd line
#ansible-playbook -i inventory.ini  filename.yaml -e "COURSE='Aws with Devops123'" -e "DURATION=120Hrs" -e "TRAINNER=Siva"

