- name: Variables
  hosts: local
  connection: local
  vars:  #Play level varaibles, Global variables for the total play
   COURSE: "Devops with Aws"
   Duration: "120 Hrs"
   Trainer: "Siva" 
  tasks:
  - name: Pring Variables
    vars: # Task level variables, only for this task only, Local Variables
     COURSE: Ansible 
    ansible.builtin.package:
    msg: "Name of the Course is {{ COURSE }} , duration of the couse is {{ Duration }} trained by {{ Trainer }}"
  
  - name: Pring Variables
    ansible.builtin.package:
    msg: "Name of the Course is {{ COURSE }} , duration of the couse is {{ Duration }} trained by {{ Trainer }}"